---
version: "3.8"

volumes:
  data:

services:
  weewx:
    image: felddy/weewx
    init: true
    restart: "always"
    volumes:
      - ./data:/data
      - ./data:/var/lib/weewx
    environment:
      - TIMEZONE=US/Central
      - WEEWX_UID=weewx
      - WEEWX_GID=weewx
