---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weewx
  namespace: wx
  labels:
    app: weewx
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-label: weewx-pod
  template:
    metadata:
      labels:
        pod-label: weewx-pod
    spec:
      containers:
      - name: weewx
        image: felddy/weewx
        env:
        - name: TIMEZONE
          value: US/Central
        - name: WEEWX_UID
          value: weewx
        - name: WEEWX_GID
          value: weewx
        volumeMounts:
        - name: weewx-storage
          mountPath: /var/lib/weewx
          subPath: storage
        - name: weewx-conf
          mountPath: /data
          subPath: conf
      volumes:
      - name: weewx-storage
        persistentVolumeClaim:
          claimName: weewx-ssd
      - name: weewx-conf
        persistentVolumeClaim:
          claimName: weewx-ssd
---
apiVersion: v1
kind: Service
metadata:
  name: weewx-web
  namespace: wx
  labels:
    app: weewx
spec:
  selector:
    pod-label: weewx-pod
  ports:
  - protocol: TCP
    port: 80
