apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mqtt-monitor
  namespace: mqtt
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
  namespaceSelector:
    any: true
  endpoints:
    - port: prometheus
      interval: 30s
    
