## media/plex.values.yml

claimToken: "claim-Sj8fkKZ-BjydTyxTkSdr" # Replace `<CLAIM_TOKEN>` by the token obtained previously.

image:
  repository: linuxserver/plex
  tag: latest
  pullPolicy: IfNotPresent

kubePlex:
  enabled: false # kubePlex (transcoder job) is disabled because not available on ARM. The transcoding will be performed by the main Plex instance instead of a separate Job.

timezone: America/Chicago

service:
  type: LoadBalancer # We will use a LoadBalancer to obtain a virtual IP that can be exposed to Plex Media via our router
  port: 32400 # Port to expose Plex

rbac:
  create: true

nodeSelector: {}

persistence:
  transcode:
    claimName: media-ssd2
  data:
    claimName: media-ssd2
  config:
    claimName: media-ssd2
  shared:
    claimName: media-ssd2

resources: {}
podAnnotations: {}
proxy:
  enable: false
