## dokuwiki/pv.yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "dokuwiki-data"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "8Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/dokuwiki"
---
