controller:
  image:
    registry: docker.io
    repository: metallb/controller
    tag: latest
speaker:
  image:
    registry: docker.io
    repository: metallb/speaker
    tag: live-website
configInline:
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.50.240-192.168.50.250

